//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Coinfx_prefab
    {
        public const string BundleName = "coinfx_prefab";
        public const string CoinFx = "CoinFx";
        public const string StarFx = "StarFx";
    }
    public class Font
    {
        public const string BundleName = "font";
        public const string SourceHanSansCNBold_SDF_OutLine = "SourceHanSansCN-Bold SDF OutLine";
    }
    public class Fontall_asset
    {
        public const string BundleName = "fontall_asset";
        public const string FontAll = "FontAll";
    }
    public class Fontextra_asset
    {
        public const string BundleName = "fontextra_asset";
        public const string FontExtra = "FontExtra";
    }
    public class Uibegin_prefab
    {
        public const string BundleName = "uibegin_prefab";
        public const string UIBegin = "UIBegin";
    }
    public class Uibeginselect_prefab
    {
        public const string BundleName = "uibeginselect_prefab";
        public const string UIBeginSelect = "UIBeginSelect";
    }
    public class Uibuyitem_prefab
    {
        public const string BundleName = "uibuyitem_prefab";
        public const string UIBuyItem = "UIBuyItem";
    }
    public class Uicontinue_prefab
    {
        public const string BundleName = "uicontinue_prefab";
        public const string UIContinue = "UIContinue";
    }
    public class Uideletelife_prefab
    {
        public const string BundleName = "uideletelife_prefab";
        public const string UIDeleteLife = "UIDeleteLife";
    }
    public class Uigetcoin_prefab
    {
        public const string BundleName = "uigetcoin_prefab";
        public const string UIGetCoin = "UIGetCoin";
    }
    public class Uilessstar_prefab
    {
        public const string BundleName = "uilessstar_prefab";
        public const string UILessStar = "UILessStar";
    }
    public class Uimask_prefab
    {
        public const string BundleName = "uimask_prefab";
        public const string UIMask = "UIMask";
    }
    public class Uimorelife_prefab
    {
        public const string BundleName = "uimorelife_prefab";
        public const string UIMoreLife = "UIMoreLife";
    }
    public class Uipersonal_prefab
    {
        public const string BundleName = "uipersonal_prefab";
        public const string UIPersonal = "UIPersonal";
    }
    public class Uiretry_prefab
    {
        public const string BundleName = "uiretry_prefab";
        public const string UIRetry = "UIRetry";
    }
    public class Uishop_prefab
    {
        public const string BundleName = "uishop_prefab";
        public const string UIShop = "UIShop";
    }
    public class Uiunlockscene_prefab
    {
        public const string BundleName = "uiunlockscene_prefab";
        public const string UIUnlockScene = "UIUnlockScene";
    }
    public class Uivictory_prefab
    {
        public const string BundleName = "uivictory_prefab";
        public const string UIVictory = "UIVictory";
    }
}
