//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Font
    {
        public const string BundleName = "font";
        public const string SourceHanSansCNBold_SDF_OutLine = "SourceHanSansCN-Bold SDF OutLine";
    }
    public class Fontall_asset
    {
        public const string BundleName = "fontall_asset";
        public const string FontAll = "FontAll";
    }
    public class Fontextra_asset
    {
        public const string BundleName = "fontextra_asset";
        public const string FontExtra = "FontExtra";
    }
    public class Uibegin_prefab
    {
        public const string BundleName = "uibegin_prefab";
        public const string UIBegin = "UIBegin";
    }
    public class Uidefeat_prefab
    {
        public const string BundleName = "uidefeat_prefab";
        public const string UIDefeat = "UIDefeat";
        public const string UIInfo = "UIInfo";
    }
}
